name: profano-data
on:
  schedule:
    - cron: 15 0 * * *
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
      - ./postprocess.ts
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://datastore.elgatoylacaja.com/payloads/xd-profano
          downloaded_filename: profano-data.json
          postprocess: ./postprocess.ts
